[package]
name = "pl_ast"
version = "0.1.0"
edition = "2021"

[lib]
name = "pl_ast"
path = "src/lib.rs"

[[bin]]
name = "pl_ast_bin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.16"
